### ISSUE TITLE
Solidity is being identified as "C"

### ISSUE THREAD

**Issue by rappie** [lassik/emacs-language-id#14]
I'm using Spacemacs with the 'solidity' layer.

When I open a `.sol` solidity file and run `language-id-buffer` it returns "C" instead of "Solidity".
If I comment out `("C" c-mode)` (line 115 in `language-id.el`) it does work and returns "Solidity".

**Comment by lassik** [comment]
Thanks for reporting this. Fix now in master; does it solve the problem?

**Comment by lassik** [comment]
Should be up to date; if you click on "Source Code" at https://melpa.org/#/language-id that version of language-id.el has the patch. Does it work if you upgrade now?

You're not using MELPA Stable by any chance?

**Comment by rappie** [comment]
Yep it works. Awesome!
Thanks :smile:
